name: CI

on:
  push:

jobs:
  # Runs a TypeScript type check
  tsc:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: npm ci --no-fund
      - name: Run tsc
        run: npm run tsc
  # Checks for dependency conflicts that `npm ci` would miss
  npm:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check dependency tree
        run: npm i --package-lock-only --dry-run
  # Builds extension
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
        browser: ['chrome', 'firefox']
        mode: ['dev', 'prod']
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: npm ci --no-fund
      - name: Build extension
        run: node --run=build -- ${{ matrix.browser }} ${{ matrix.mode }}
  # Runs tests
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: npm ci --no-fund
      - name: Run tests
        run: npm test
